//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetGB3
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlumnoSet()
        {
            this.EvaluacionesSet = new HashSet<EvaluacionesSet>();
        }
    
        public int ID { get; set; }
        public int CursoID { get; set; }
        public string Nombre { get; set; }
        public string Edad { get; set; }
        public string Genero { get; set; }
        public int Apoderado_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionesSet> EvaluacionesSet { get; set; }
        public virtual UsuarioSet_Apoderado UsuarioSet_Apoderado { get; set; }
        public virtual CursoSet CursoSet { get; set; }
    }
}
