//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetGB3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivos
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Tipo_archivo { get; set; }
        public string Ruta { get; set; }
        public int ActividadesSetID { get; set; }
    
        public virtual ActividadesSet ActividadesSet { get; set; }
    }
}
