//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetGB3
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CursoSet()
        {
            this.AlumnoSet = new HashSet<AlumnoSet>();
            this.UsuarioSet_Educadora = new HashSet<UsuarioSet_Educadora>();
        }
    
        public int ID { get; set; }
        public int ProgramasID { get; set; }
        public string Nivel { get; set; }
        public string Sala { get; set; }
        public string Periodo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlumnoSet> AlumnoSet { get; set; }
        public virtual ProgramasSet ProgramasSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioSet_Educadora> UsuarioSet_Educadora { get; set; }
    }
}
