//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetGB3
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionesSet
    {
        public int ID { get; set; }
        public int ActividadesID { get; set; }
        public int Calificaciones { get; set; }
        public int AlumnoID { get; set; }
    
        public virtual ActividadesSet ActividadesSet { get; set; }
        public virtual AlumnoSet AlumnoSet { get; set; }
    }
}
