//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetGB3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_GBEntities : DbContext
    {
        public BD_GBEntities()
            : base("name=BD_GBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActividadesSet> ActividadesSet { get; set; }
        public virtual DbSet<AdministradorSet> AdministradorSet { get; set; }
        public virtual DbSet<AlumnoSet> AlumnoSet { get; set; }
        public virtual DbSet<CursoSet> CursoSet { get; set; }
        public virtual DbSet<EvaluacionesSet> EvaluacionesSet { get; set; }
        public virtual DbSet<ProgramasSet> ProgramasSet { get; set; }
        public virtual DbSet<UsuarioSet> UsuarioSet { get; set; }
        public virtual DbSet<Archivos> ArchivosSet { get; set; }
    }
}
